pipeline {
  agent any

 // tools {
 //   terraform 'Terraform_1.7' // You must define this in Jenkins -> Global Tools
 // }

  environment {
   
    AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
    AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    BACKEND_DIR = "backend"
    MAIN_DIR = "aws"
  }

  stages {
    stage('Checkout') {
      steps {
       git branch: 'main', url: 'https://github.com/coach4u/terraform.git'
      }
    }

    stage('Create Backend') {
      steps {
        dir("${BACKEND_DIR}") {
          sh '''
            terraform init
            terraform apply -auto-approve
          '''
        }
      }
    }

    stage('Init Infra with Remote Backend') {
      steps {
        dir("${MAIN_DIR}") {
          sh '''
            terraform init
            terraform plan
          '''
        }
      }
    }

    stage('Apply Infrastructure') {
      steps {
        dir("${MAIN_DIR}") {
          sh 'terraform apply -auto-approve'
        }
      }
    }
  }
}
